### ISSUE TITLE
Unlikely benchmarked?

### ISSUE THREAD

**Issue by L3P3** [seritools/q565#2]
https://github.com/seritools/q565/blob/main/q565/src/streaming_no_header.rs#L87

In computer generated images, run length encoding is not that unlikely at all, why have you added this to this opcode? I only see 0xff being unlikely since it only appears once. (Could be also ignored if input stream is cut by last byte!)

(And btw, great project, loved reading it!)

**Comment by seritools** [comment]
That particular very specific ordering + unlikely gave a big perf improvement on my system because it coaxed LLVM to not generate a jump table but to a regular branching check, IIRC.
But yeah, mostly premature optimization because it's fun, will probably remove it sooner rather than later x) 

> (And btw, great project, loved reading it!)

Thanks! Hopyefully getting around to cleaning it up a bit more, soon. ^^

**Comment by L3P3** [comment]
When you actually tested before and after, then I take back everything, I do not mind such stuff if it is tested!

**Comment by seritools** [comment]
Removed `unlikely` for now again
